# Generated by Django 3.0.8 on 2020-07-30 23:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Port',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin', models.CharField(max_length=128, unique=True)),
                ('name', models.CharField(max_length=64)),
                ('comment', models.CharField(blank=True, max_length=192)),
                ('maintainer', models.EmailField(max_length=254)),
                ('www', models.URLField(blank=True)),
                ('main_category', models.CharField(max_length=64)),
                ('categories', models.ManyToManyField(to='ports.Category')),
            ],
        ),
        migrations.CreateModel(
            name='Fallout',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('env', models.CharField(max_length=48)),
                ('version', models.CharField(max_length=24)),
                ('category', models.CharField(max_length=48)),
                ('maintainer', models.EmailField(max_length=254)),
                ('last_committer', models.EmailField(max_length=254)),
                ('date', models.DateTimeField()),
                ('log_url', models.URLField()),
                ('build_url', models.URLField()),
                ('report_url', models.URLField()),
                ('server', models.CharField(blank=True, max_length=48)),
                ('port', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ports.Port')),
            ],
        ),
    ]
