# Generated by Django 3.1.2 on 2020-10-31 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ports', '0002_server'),
    ]

    operations = [
        migrations.AddField(
            model_name='fallout',
            name='flavor',
            field=models.CharField(blank=True, max_length=24),
        ),
    ]
